indent = 4
margin = 80
always_for_in = false
whitespace_typedefs = false
whitespace_ops_in_indices = false
remove_extra_newlines = true
import_to_using = false
pipe_to_function_call = false
short_to_long_function_def = false
always_use_return = false
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = true
format_docstrings = true
align_struct_field = true
align_conditional = false
align_assignment = true
align_pair_arrow = true
conditional_to_if = false
normalize_line_endings = "auto"
verbose = true
style = "yas"
